#!/bin/bash
clear
init_abaqus_subroutine

job="unit_shear"
job="unit_exp"

flags="job=$job user=VUMAT.f double int ask_delete=off"

echo "Command: abaqus "$flags
abaqus $flags

rm -f *.com *.mdl *.pac *.res *.stt *.src *.sel *.mdl *.prt *.abq *.exception *.msg

