#!/bin/bash
clear
init_abaqus_subroutine

#ifort VUMAT_ex1.f -o VUMAT_ex1.o -DDEBUG 
abaqus double job=unit_exp user=VUMAT_ex1.f int ask_delete=off

#abaqus double job=unit_exp.inp int ask_delete=off

rm -f *.com *.mdl *.pac *.res *.stt *.src *.sel *.mdl *.prt *.abq *.exception
